controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      
    differential_system_controller:
      type: differential_system_controller/DifferentialSystemController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names  : ['wheel_FL_joint', 'wheel_RL_joint']
    right_wheel_names : ['wheel_FR_joint', 'wheel_RR_joint']

    wheel_separation : 0.358
    wheel_radius : 0.0625
    wheel_separation_multiplier : 1.0
    left_wheel_radius_multiplier : 1.0
    right_wheel_radius_multiplier : 1.0

    odom_frame_id: odom
    base_frame_id: base_footprint

    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    enable_odom_tf: true

    cmd_vel_timeout: 3.0
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    # limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 6.0
    linear.x.min_velocity: -6.0
    linear.x.max_acceleration: 2.5
    linear.x.min_acceleration: -2.5
    linear.x.max_jerk: 0.5
    linear.x.min_jerk: -0.5

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 6.0
    angular.z.min_velocity: -6.0
    angular.z.max_acceleration: 3.0
    angular.z.min_acceleration: -3.0
    angular.z.max_jerk: 0.5
    angular.z.min_jerk: -0.5

differential_system_controller:
  ros__parameters:
    left_joint_name  : 'rocker_L_joint'
    right_joint_name : 'rocker_R_joint'
    force_constant : 20.0

